spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/student_rest
    username: skd
    password: password
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          import_files: data-postgres.sql

server:
  servlet:
    context-path: /dev
