spring:
  profiles:
    active:
      - dev
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    com:
      org:
       springframework: DEBUG
    org:
      hibernate:
        SQL: DEBUG

server:
  port: 8080
  servlet:
    context-path: /docker-demo
