spring:
  datasource:
#    platform: test
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: password
    initialization-mode: always

  jpa:
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          import_files: data-test.sql

  h2:
    console.enabled: true

server:
  servlet:
    context-path: /test




